[package]
name = "rgb"
version = "0.0.1"
authors = ["Aurelien Vallee <vallee.aurelien@gmail.com>"]
build = "build.rs"

[dependencies]
lazy_static = "0.1.*"
getopts = "0.2.*"

[dependencies.linenoise]
git = "https://github.com/cmr/linenoise-rs.git"
